# Generated by Django 4.0 on 2021-12-20 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_message_read_at_message_sent_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='text',
        ),
    ]
