# Generated by Django 4.0 on 2021-12-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_description_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(db_table='web_followers', related_name='follow_to', to='web.User'),
        ),
    ]
